jwt:
  secret: studya23423room8vmfhwprxm291peoples17
  access:
    expiration: 3600 #초단위
    header: AccessToken

  refresh:
    expiration: 3600 #초단위
    header: RefreshToken

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 908e8fd87931e80b9e30541678019c59
            client-secret: FxlqXPhOmTsDeh7G1kYa9dH1soiv6FpX
            redirect-uri: http://localhost:8082/api/v1/login/oauth/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
          naver:
            client-id: TafpcVX1tY9l2WXpW33M
            client-secret: D10krBe0nX
            redirect-uri:  http://13.209.99.229:8082/api/v1/login/oauth/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
