spring:
  profiles:
    group:
      "dev": "dev, common, jwt, email"
      "prod": "prod ,common, jwt, email, awsMysql"

---
spring:
  config:
    activate:
      on-profile: "common"

  thymeleaf:
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studya
    username: root
    password: root

logging:
  level:
    '[com.peoples.api]': DEBUG
    '[org.springframework]': INFO
    '[org.springframework.data.elasticsearch.client.WIRE]': TRACE
---
spring:
  config:
    activate:
      on-profile: "prod"

logging:
  level:
    root: ERROR
    '[com.peoples.api]': INFO