spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://peoples.cp64x6kqbjeh.ap-northeast-2.rds.amazonaws.com:3306/peoples
    username: peoples
    password: peoples!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: true

  profiles:
    include: jwt

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    '[com.peoples.api]': DEBUG
    '[org.springframework]': INFO
    '[org.springframework.data.elasticsearch.client.WIRE]': TRACE

server:
  port: 8082